#!/bin/bash

# Update brew
function update_brew() {
    brew update
    brew upgrade
    brew cleanup
}


function update_brew_cask() {
    brew cask update
    brew cask cleanup
}

# Update OSX and brew
function update() {
    echo "$fg[yellow]Find Apple software updates$reset_color"
    sudo softwareupdate -i -a
    echo "$fg[yellow]Update brew and its packages$reset_color"
    update_brew
    echo "$fg[yellow]Update brew cask and its packages$reset_color"
    update_brew_cask
}

# Create a new directory and cd into it
function mkd() {
    mkdir -p "$1" 
    cd "$1"
}

# Compiles a .c
function gccc {
    gcc "$1".c -o "$1"
    echo "Compiled $1"
}

# Compiles and run a .c
function gccr {
    gccc "$1"
    echo
    ./"$1"
    rm "$1"
    echo
    echo "Removed $1"
}

function gshpsh {
    echo "\e[93mgit stash\e[0m"
    g stash
    echo ""
    echo "\e[93mgit pull --rebase\e[0m"
    g pull --rebase
    echo ""
    echo "\e[93mgit stash pop\e[0m"
    g stash pop
}

