#!/bin/bash

# Update brew
function update_brew() {
    brew update
    brew upgrade
    brew cleanup
}


function update_brew_cask() {
    brew cask update
    brew cask cleanup
}

# Update gems
function update_gems() {
    gem update --system
    gem update
}

# Update OSX and brew
function update() {
    echo "$fg[yellow]Find Apple software updates$reset_color"
    sudo softwareupdate -i -a
    echo "$fg[yellow]Update brew and its packages$reset_color"
    update_brew
    echo "$fg[yellow]Update brew cask and its packages$reset_color"
    update_brew_cask
    echo "$fg[yellow]Update gems$reset_color"
    update_gems
}

# Create a new directory and cd into it
function mkd() {
    mkdir -p "$1" 
    cd "$1"
}

# Compiles a .c
function gccc {
    gcc "$1".c -o "$1"
    echo "Compiled $1"
}

# Compiles and run a .c
function gccr {
    gccc "$1"
    echo
    ./"$1"
    rm "$1"
    echo
    echo "Removed $1"
}

function psgmsn {
    curl --data "$1 <img src=$2></img>" http://vault.alanorozco.com/anarchy/\?pinshits
}

function gshpsh {
    echo "\e[93mgit stash\e[0m"
    g stash
    echo ""
    echo "\e[93mgit pull --rebase\e[0m"
    g pull --rebase
    echo ""
    echo "\e[93mgit stash pop\e[0m"
    g stash pop
}

# Java settings
alias j6='ju 1.6'
alias j7='ju 1.7'

function jls() {
    echo "Use ´j6 and j7´ to conventiently switch between Java versions."
    echo "For a specific version use ´ju <version>´ where available versions are listed below:"
    /usr/libexec/java_home -V 2>&1 | grep -E "\d.\d.\d" | cut -d , -f 1 | colrm 1 4 | grep -v Home
}

function ju() {
    export JAVA_HOME=$(/usr/libexec/java_home -v $1)
    export PATH=$JAVA_HOME/bin:$PATH
    java -version
}

# Run IMA Test
fuction rit() {
    make-dbg third_party_player_dev/test_GoogleIMAAdsManagerModule 
    run-air third_party_player_dev/test_GoogleIMAAdsManagerModule
}

